# Generated by Django 3.2 on 2021-04-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0005_auto_20210423_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
