# Generated by Django 3.2 on 2021-05-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name_plural': 'WhyChooseUs'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
